## Pandas
Pandas is a package used for managing data.

Pandas main use is that it creates 2 new data types for storing data: series and dataframe.

data frame - excel spreadsheet like rows and coulms
series - one individual column

Think of a pandas dataframe like an excel spreadsheet that is storing some data. One column can have customer name, one column can have product sold name, another column can have price or quantity... Then the rows could be individual sales.

A dataframe is made up of several series. Each column of a dataframe is a series.

We can name each column and row of a dataframe.

A pandas dataframe is very similar to a data.frame in R.

Similar to numpy arrays, a dataframe is a more robust data type for storing data than lists of lists. Dataframes are more flexible than numpy arrays.

A numpy array can create a matrix with all entries of the same data type. In a dataframe each column can have its own datatype.

That's not to say numpy arrays aren't useful. It is often easiest to convert some subset of a dataframe to a numpy array and then use that to do some math.

Pandas also has SQL-like functions for merging, joining, and sorting dataframes.

In [1]:
import pandas as pd
import numpy as np  # numpy is not necessary for pandas, but we will use some np code in this example
# in general it's good practice to import all pacakages at the beginning

In [2]:
# first let's look at series - think of this as a single column of a spreadsheet
# each entry in a series corresponds to an individual row in the spreadsheet
# we can create a series by converting a list, or numpy array

mylist = [5.4,6.1,1.7,99.8]
myarray = np.array(mylist)

In [3]:
myseries1 = pd.Series(data=mylist)
print(myseries1)
myseries2 = pd.Series(data=myarray)
print(myseries2)

0     5.4
1     6.1
2     1.7
3    99.8
dtype: float64
0     5.4
1     6.1
2     1.7
3    99.8
dtype: float64

In [4]:
# we access individual entries the same way as with lists and arrays
print(myseries1[2])

1.7

In [5]:
# we can add labels to the entries of a series

mylabels = ['first','second','third','fourth']
myseries3 = pd.Series(data=mylist,index=mylabels)
print(myseries3)

first      5.4
second     6.1
third      1.7
fourth    99.8
dtype: float64

In [6]:
# we need not be explicit about the entries of pd.Series
myseries4 = pd.Series(mylist,mylabels)
print(myseries4)

first      5.4
second     6.1
third      1.7
fourth    99.8
dtype: float64

In [7]:
# we can also access entries using the index labels
print(myseries4['second'])

6.1

In [8]:
# we can do math on series 
myseries5 = pd.Series([5.5,1.1,8.8,1.6],['first','third','fourth','fifth'])
print(myseries5)
print('')
print(myseries5+myseries4)

first     5.5
third     1.1
fourth    8.8
fifth     1.6
dtype: float64

fifth       NaN
first      10.9
fourth    108.6
second      NaN
third       2.8
dtype: float64

In [9]:
# we can combine series to create a dataframe using the concat function
df1 = pd.concat([myseries4,myseries5],axis=1,sort=False)
# axis is nothing but in oythin indexing starts from the 0 and axis =0 is rows and axis =1 is coulmns
# sort is like to sort in the albabetical order
df1

           0    1
first    5.4  5.5
second   6.1  NaN
third    1.7  1.1
fourth  99.8  8.8
fifth    NaN  1.6

In [10]:
# we can create a new dataframe 
df2 = pd.DataFrame(np.random.randn(5,5))
df2

          0         1         2         3         4
0  0.582122 -0.260337 -0.188750 -1.017805 -1.951595
1 -0.538011  0.807593  2.097124 -2.171795  0.416944
2 -0.026631 -0.805104  0.777748 -0.998365  0.594445
3 -0.016529 -0.360159  1.186499 -1.459519 -0.406963
4 -0.429331 -0.025433  1.141285 -0.076441  1.421894

In [11]:
# lets give labels to rows and columns
df3 = pd.DataFrame(np.random.randn(5,5),index=['first row','second row','third row','fourth row','fifth row'],
                   columns=['first col','second col','third col','fourth col','fifth col'])
df3

            first col  second col  third col  fourth col  fifth col
first row   -0.503463    1.035259   0.322884   -0.456392  -1.890019
second row   0.312832    0.665123   0.683438    2.274254  -0.562391
third row    1.113435   -0.098200  -0.451298   -1.569351  -1.606551
fourth row  -0.641069    0.287119  -1.615631    0.039812   0.205152
fifth row    0.912991    0.329561  -1.181276    0.399547  -0.445795

# acceesing and modifying data frames

In [12]:
# we can access individual series in a data frame
print(df3['second col'])
print('')
df3[['third col','first col']]

first row     1.035259
second row    0.665123
third row    -0.098200
fourth row    0.287119
fifth row     0.329561
Name: second col, dtype: float64

            third col  first col
first row    0.322884  -0.503463
second row   0.683438   0.312832
third row   -0.451298   1.113435
fourth row  -1.615631  -0.641069
fifth row   -1.181276   0.912991

In [13]:
# we can access rows of a dataframe
df3.loc['fourth row']

first col    -0.641069
second col    0.287119
third col    -1.615631
fourth col    0.039812
fifth col     0.205152
Name: fourth row, dtype: float64

In [14]:
df3.iloc[2]

first col     1.113435
second col   -0.098200
third col    -0.451298
fourth col   -1.569351
fifth col    -1.606551
Name: third row, dtype: float64

In [15]:
df3.loc[['fourth row','first row'],['second col','third col']]

            second col  third col
fourth row    0.287119  -1.615631
first row     1.035259   0.322884

In [16]:
# we can use logical indexing for dataframes just like for numpy arrays
df3>0

            first col  second col  third col  fourth col  fifth col
first row       False        True       True       False      False
second row       True        True       True        True      False
third row        True       False      False       False      False
fourth row      False        True      False        True       True
fifth row        True        True      False        True      False

In [17]:
print(df3[df3>0])

            first col  second col  third col  fourth col  fifth col
first row         NaN    1.035259   0.322884         NaN        NaN
second row   0.312832    0.665123   0.683438    2.274254        NaN
third row    1.113435         NaN        NaN         NaN        NaN
fourth row        NaN    0.287119        NaN    0.039812   0.205152
fifth row    0.912991    0.329561        NaN    0.399547        NaN

In [18]:
# we can add columns to a dataframe
df3['sixth col'] = np.random.randn(5,1)
df3

            first col  second col  third col  fourth col  fifth col  sixth col
first row   -0.503463    1.035259   0.322884   -0.456392  -1.890019  -0.134337
second row   0.312832    0.665123   0.683438    2.274254  -0.562391  -0.523201
third row    1.113435   -0.098200  -0.451298   -1.569351  -1.606551   0.127287
fourth row  -0.641069    0.287119  -1.615631    0.039812   0.205152   1.104388
fifth row    0.912991    0.329561  -1.181276    0.399547  -0.445795   0.061630

In [19]:
# we can remove columns or rows from a dataframe
df3.drop('first col',axis=1,inplace=True)

In [20]:
df3

            second col  third col  fourth col  fifth col  sixth col
first row     1.035259   0.322884   -0.456392  -1.890019  -0.134337
second row    0.665123   0.683438    2.274254  -0.562391  -0.523201
third row    -0.098200  -0.451298   -1.569351  -1.606551   0.127287
fourth row    0.287119  -1.615631    0.039812   0.205152   1.104388
fifth row     0.329561  -1.181276    0.399547  -0.445795   0.061630

In [21]:
df4 = df3.drop('first col',axis=1)
df4

KeyError: "['first col'] not found in axis"

In [22]:
df5 = df3.drop('second row',axis=0)
df5

            second col  third col  fourth col  fifth col  sixth col
first row     1.035259   0.322884   -0.456392  -1.890019  -0.134337
third row    -0.098200  -0.451298   -1.569351  -1.606551   0.127287
fourth row    0.287119  -1.615631    0.039812   0.205152   1.104388
fifth row     0.329561  -1.181276    0.399547  -0.445795   0.061630

In [23]:
# we can remove a dataframe's index labels
df5.reset_index()

        index  second col  third col  fourth col  fifth col  sixth col
0   first row    1.035259   0.322884   -0.456392  -1.890019  -0.134337
1   third row   -0.098200  -0.451298   -1.569351  -1.606551   0.127287
2  fourth row    0.287119  -1.615631    0.039812   0.205152   1.104388
3   fifth row    0.329561  -1.181276    0.399547  -0.445795   0.061630

In [24]:
df5

            second col  third col  fourth col  fifth col  sixth col
first row     1.035259   0.322884   -0.456392  -1.890019  -0.134337
third row    -0.098200  -0.451298   -1.569351  -1.606551   0.127287
fourth row    0.287119  -1.615631    0.039812   0.205152   1.104388
fifth row     0.329561  -1.181276    0.399547  -0.445795   0.061630

In [25]:
df5.reset_index(inplace=True)
df5

        index  second col  third col  fourth col  fifth col  sixth col
0   first row    1.035259   0.322884   -0.456392  -1.890019  -0.134337
1   third row   -0.098200  -0.451298   -1.569351  -1.606551   0.127287
2  fourth row    0.287119  -1.615631    0.039812   0.205152   1.104388
3   fifth row    0.329561  -1.181276    0.399547  -0.445795   0.061630

In [26]:
# we can assign new names to the index
df5['new name'] = ['This','is','the','row']
df5

,index,second col,third col,fourth col,fifth col,sixth col,new name
0,first row,1.035259,0.322884,-0.456392,-1.890019,-0.134337,This
1,third row,-0.098200,-0.451298,-1.569351,-1.606551,0.127287,is
2,fourth row,0.287119,-1.615631,0.039812,0.205152,1.104388,the
3,fifth row,0.329561,-1.181276,0.399547,-0.445795,0.061630,row

In [27]:
df5.set_index('new name',inplace=True)
df5

               index  second col  third col  fourth col  fifth col  sixth col
new name
This       first row    1.035259   0.322884   -0.456392  -1.890019  -0.134337
is         third row   -0.098200  -0.451298   -1.569351  -1.606551   0.127287
the       fourth row    0.287119  -1.615631    0.039812   0.205152   1.104388
row        fifth row    0.329561  -1.181276    0.399547  -0.445795   0.061630

# Combining data frames
The ways dataframes are combined in pandas is similar to SQL

We will examine 3 methods for combining dataframes

concat
join
merge

In [29]:
df7 = pd.DataFrame({"customer":['101','102','103','104'], 
                    'category': ['cat2','cat2','cat1','cat3'],
                    'important': ['yes','no','yes','yes'],
                    'sales': [123,52,214,663]},index=[0,1,2,3])

df8 = pd.DataFrame({"customer":['101','103','104','105'], 
                    'color': ['yellow','green','green','blue'],
                    'distance': [12,9,44,21],
                    'sales': [123,214,663,331]},index=[4,5,6,7])

In [30]:
pd.concat([df7,df8],axis=0,sort=False)

  customer category important  sales   color  distance
0      101     cat2       yes    123     NaN       NaN
1      102     cat2        no     52     NaN       NaN
2      103     cat1       yes    214     NaN       NaN
3      104     cat3       yes    663     NaN       NaN
4      101      NaN       NaN    123  yellow      12.0
5      103      NaN       NaN    214   green       9.0
6      104      NaN       NaN    663   green      44.0
7      105      NaN       NaN    331    blue      21.0

In [31]:
pd.concat([df7,df8],axis=0,sort=True)

  category   color customer  distance important  sales
0     cat2     NaN      101       NaN       yes    123
1     cat2     NaN      102       NaN        no     52
2     cat1     NaN      103       NaN       yes    214
3     cat3     NaN      104       NaN       yes    663
4      NaN  yellow      101      12.0       NaN    123
5      NaN   green      103       9.0       NaN    214
6      NaN   green      104      44.0       NaN    663
7      NaN    blue      105      21.0       NaN    331

In [32]:
pd.concat([df7,df8],axis=1,sort=False)

  customer category important  sales customer   color  distance  sales
0      101     cat2       yes  123.0      NaN     NaN       NaN    NaN
1      102     cat2        no   52.0      NaN     NaN       NaN    NaN
2      103     cat1       yes  214.0      NaN     NaN       NaN    NaN
3      104     cat3       yes  663.0      NaN     NaN       NaN    NaN
4      NaN      NaN       NaN    NaN      101  yellow      12.0  123.0
5      NaN      NaN       NaN    NaN      103   green       9.0  214.0
6      NaN      NaN       NaN    NaN      104   green      44.0  663.0
7      NaN      NaN       NaN    NaN      105    blue      21.0  331.0

# Merge and Join
Merge combines dataframes using a column's values to identify common entries

Join combines dataframes using the index to identify common entries

In [33]:
pd.merge(df7,df8,how='outer',on='customer') # outer merge is union of on

  customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes    123.0  yellow      12.0    123.0
1      102     cat2        no     52.0     NaN       NaN      NaN
2      103     cat1       yes    214.0   green       9.0    214.0
3      104     cat3       yes    663.0   green      44.0    663.0
4      105      NaN       NaN      NaN    blue      21.0    331.0

In [34]:
pd.merge(df7,df8,how='inner',on='customer') # inner merge is intersection of on

  customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes      123  yellow        12      123
1      103     cat1       yes      214   green         9      214
2      104     cat3       yes      663   green        44      663

In [35]:
pd.merge(df7,df8,how='right',on='customer') # left merge is just first on, but all columns ... right is second

  customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes    123.0  yellow        12      123
1      103     cat1       yes    214.0   green         9      214
2      104     cat3       yes    663.0   green        44      663
3      105      NaN       NaN      NaN    blue        21      331

In [36]:
df9 = pd.DataFrame({'Q1': [101,102,103],
                    'Q2': [201,202,203]},
                   index=['I0','I1','I2'])

df10 = pd.DataFrame({'Q3': [301,302,303],
                    'Q4': [401,402,403]},
                   index=['I0','I2','I3'])

In [37]:
# join behaves just like merge, 
# except instead of using the values of one of the columns 
# to combine data frames, it uses the index labels
df9.join(df10,how='right') # outer, inner, left, and right work the same as merge

       Q1     Q2   Q3   Q4
I0  101.0  201.0  301  401
I2  103.0  203.0  302  402
I3    NaN    NaN  303  403

In [38]:
# let's now go over a few more basic functialities of pandas

df8['color'].unique()

array(['yellow', 'green', 'blue'], dtype=object)

In [39]:
df8['color'].value_counts()

color
green     2
yellow    1
blue      1
Name: count, dtype: int64

In [40]:
df9.mean()

Q1    102.0
Q2    202.0
dtype: float64

In [41]:
df8.columns

Index(['customer', 'color', 'distance', 'sales'], dtype='object')

In [42]:
df8

  customer   color  distance  sales
4      101  yellow        12    123
5      103   green         9    214
6      104   green        44    663
7      105    blue        21    331

In [43]:
new_df = df8[(df8['customer']!='105') & (df8['color']!='green')]
new_df

  customer   color  distance  sales
4      101  yellow        12    123

In [44]:
print(df8['sales'].sum())
print(df8['distance'].min())

1331
9

In [45]:
def profit(s):
    return s*0.5 # 50% markup...

In [46]:
df8['sales'].apply(profit)

4     61.5
5    107.0
6    331.5
7    165.5
Name: sales, dtype: float64

In [47]:
df8['color'].apply(len)

4    6
5    5
6    5
7    4
Name: color, dtype: int64

In [48]:
df11 = df8[['distance','sales']]
df11.applymap(profit)

/var/folders/lf/j6lhwfl96ssgpp9bdtfm9r640000gn/T/ipykernel_1005/1490032296.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df11.applymap(profit)

   distance  sales
4       6.0   61.5
5       4.5  107.0
6      22.0  331.5
7      10.5  165.5

In [49]:
def col_sum(co):
    return sum(co)
df11.apply(col_sum)

distance      86
sales       1331
dtype: int64

In [50]:
df11.applymap(col_sum)

/var/folders/lf/j6lhwfl96ssgpp9bdtfm9r640000gn/T/ipykernel_1005/362015604.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df11.applymap(col_sum)

TypeError: 'int' object is not iterable

In [51]:
del df8['color']
df8

  customer  distance  sales
4      101        12    123
5      103         9    214
6      104        44    663
7      105        21    331

In [52]:
df8.index

Index([4, 5, 6, 7], dtype='int64')

In [53]:
df8.sort_values(by='distance',inplace=True)
df8

  customer  distance  sales
5      103         9    214
4      101        12    123
7      105        21    331
6      104        44    663

In [54]:
df8

  customer  distance  sales
5      103         9    214
4      101        12    123
7      105        21    331
6      104        44    663

In [55]:
# if some series has multiple of the same value then we can group all the unique entries together
mydict = {'customer': ['Customer 1','Customer 1','Customer2','Customer2','Customer3','Customer3'], 
          'product1': [1.1,2.1,3.8,4.2,5.5,6.9],
          'product2': [8.2,9.1,11.1,5.2,44.66,983]}
df6 = pd.DataFrame(mydict,index=['Purchase 1','Purchase 2','Purchase 3','Purchase 4','Purchase 5','Purchase 6'])
df6

              customer  product1  product2
Purchase 1  Customer 1       1.1      8.20
Purchase 2  Customer 1       2.1      9.10
Purchase 3   Customer2       3.8     11.10
Purchase 4   Customer2       4.2      5.20
Purchase 5   Customer3       5.5     44.66
Purchase 6   Customer3       6.9    983.00

In [56]:
grouped_data = df6.groupby('customer')
print(grouped_data)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x137b96510>

In [57]:
grouped_data.std()

            product1    product2
customer
Customer 1  0.707107    0.636396
Customer2   0.282843    4.171930
Customer3   0.989949  663.506577

In [59]:
df8

  customer  distance  sales
5      103         9    214
4      101        12    123
7      105        21    331
6      104        44    663

In [60]:
df8

  customer  distance  sales
5      103         9    214
4      101        12    123
7      105        21    331
6      104        44    663

In [61]:
# similar to numpy arrays, we can also save and load dataframes to csv files, and also Excel files

df8.to_csv('df8.csv',index=True)

In [62]:
new_df8 = pd.read_csv('df8.csv',index_col=0)
new_df8

   customer  distance  sales
5       103         9    214
4       101        12    123
7       105        21    331
6       104        44    663

In [63]:
df8.to_excel('df8.xlsx',index=False,sheet_name='first sheet')
newer_df8 = pd.read_excel('df8.xlsx',sheet_name='first sheet',index_col=1)
newer_df8

          customer  sales
distance
9              103    214
12             101    123
21             105    331
44             104    663

# Explanation of this ipnyb file
# Explanation of Your Pandas Notebook

Your notebook teaches the basics of **Pandas** and some **NumPy** operations.

---

# 1. Importing Libraries

```python
import pandas as pd
import numpy as np
```

* `pandas` → used for tables/data analysis
* `numpy` → used for arrays and numerical operations

Convention:

* `pd` means pandas
* `np` means numpy

---

# 2. Series

A **Series** is a single column of data.

Example:

```python
mylist = [5.4,6.1,1.7,99.8]
myseries1 = pd.Series(data=mylist)
```

Output:

```text
0     5.4
1     6.1
2     1.7
3    99.8
```

Left side = index
Right side = value

---

# 3. Accessing Elements

```python
myseries1[2]
```

Gets value at index `2`.

Output:

```python
1.7
```

---

# 4. Custom Labels

```python
mylabels = ['first','second','third','fourth']
myseries3 = pd.Series(data=mylist,index=mylabels)
```

Now indexes become:

```text
first     5.4
second    6.1
third     1.7
fourth   99.8
```

Access using label:

```python
myseries4['second']
```

---

# 5. Series Math

```python
myseries5 + myseries4
```

Pandas adds matching labels together.

If labels don't match:

* result becomes `NaN`

`NaN` means:

> missing value

---

# 6. DataFrame

A **DataFrame** is a table (rows + columns).

```python
df2 = pd.DataFrame(np.random.randn(5,5))
```

Creates:

* 5 rows
* 5 columns
* random values

---

# 7. Row and Column Labels

```python
df3 = pd.DataFrame(
    np.random.randn(5,5),
    index=['first row',...],
    columns=['first col',...]
)
```

Now dataframe has named rows and columns.

---

# 8. Accessing Columns

```python
df3['second col']
```

Gets one column (a Series).

Multiple columns:

```python
df3[['third col','first col']]
```

Double brackets because multiple columns return a dataframe.

---

# 9. Accessing Rows

Using labels:

```python
df3.loc['fourth row']
```

Using integer positions:

```python
df3.iloc[2]
```

* `loc` → label-based
* `iloc` → position-based

---

# 10. Selecting Specific Rows and Columns

```python
df3.loc[['fourth row','first row'],
        ['second col','third col']]
```

Gets:

* selected rows
* selected columns

---

# 11. Logical Indexing

```python
df3 > 0
```

Returns:

* `True` for positive numbers
* `False` otherwise

Filtering:

```python
df3[df3 > 0]
```

Only positive values remain.

---

# 12. Adding Columns

```python
df3['sixth col'] = np.random.randn(5,1)
```

Creates a new column.

---

# 13. Dropping Columns

```python
df3.drop('first col', axis=1, inplace=True)
```

* `axis=1` → columns
* `inplace=True` → permanently change dataframe

Without `inplace=True`:

* original dataframe stays unchanged

---

# 14. Dropping Rows

```python
df5 = df3.drop('second row', axis=0)
```

* `axis=0` → rows

---

# 15. Resetting Index

```python
df5.reset_index()
```

Old labels become normal column.

---

# 16. Setting New Index

```python
df5.set_index('new name', inplace=True)
```

Makes column `'new name'` become row labels.

---

# 17. Concatenation

```python
pd.concat([df7,df8], axis=0)
```

Stacks dataframes vertically.

```python
axis=1
```

joins side-by-side.

---

# 18. Merge

```python
pd.merge(df7,df8,how='inner',on='customer')
```

Combines dataframes using common column.

## Types

### Inner Merge

Only matching rows.

### Outer Merge

All rows from both tables.

### Left Merge

All rows from first table.

### Right Merge

All rows from second table.

---

# 19. Join

```python
df9.join(df10)
```

Like merge, but uses index labels instead of columns.

---

# 20. Unique Values

```python
df8['color'].unique()
```

Returns unique entries.

---

# 21. Value Counts

```python
df8['color'].value_counts()
```

Counts frequency of each value.

---

# 22. Mean

```python
df9.mean()
```

Calculates column averages.

---

# 23. Filtering Data

```python
new_df = df8[
 (df8['customer']!='105') &
 (df8['color']!='green')
]
```

Conditions:

* customer not 105
* color not green

`&` means AND.

---

# 24. Sum and Min

```python
df8['sales'].sum()
df8['distance'].min()
```

* total sales
* smallest distance

---

# 25. Apply Function

```python
def profit(s):
    return s*0.5
```

Apply to column:

```python
df8['sales'].apply(profit)
```

Runs function on every value.

---

# 26. applymap()

```python
df11.applymap(profit)
```

Applies function to every cell in dataframe.

---

# 27. Delete Column

```python
del df8['color']
```

Removes column permanently.

---

# 28. Sorting

```python
df8.sort_values(by='distance')
```

Sort dataframe using column values.

---

# 29. GroupBy

```python
grouped_data = df6.groupby('customer')
```

Groups rows with same customer.

Then:

```python
grouped_data.std()
```

computes statistics for each group.

---

# 30. Save to CSV

```python
df8.to_csv('df8.csv')
```

Saves dataframe to CSV file.

Load again:

```python
pd.read_csv('df8.csv')
```

---

# 31. Excel Files

Save:

```python
df8.to_excel('df8.xlsx')
```

Load:

```python
pd.read_excel('df8.xlsx')
```

---

# Main Concepts Learned

| Topic     | Meaning                    |
| --------- | -------------------------- |
| Series    | single column              |
| DataFrame | table                      |
| loc       | label indexing             |
| iloc      | position indexing          |
| concat    | combine tables             |
| merge     | SQL-style join             |
| groupby   | grouping data              |
| apply     | run function on column     |
| applymap  | run function on every cell |
| to_csv    | save CSV                   |
| read_csv  | load CSV                   |